#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
export GOWORK=off
export GOCACHE="${GOCACHE:-${TMPDIR:-/tmp}/desktop-world-go-cache}"
go test -race ./...
go vet ./...
GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build ./cmd/dtw-helper ./internal/platform/... ./internal/world/...
GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go vet ./cmd/dtw-helper ./internal/platform/... ./internal/world/...
go build ./cmd/dtw ./cmd/dtw-helper
